using System.Data;
using System.Windows.Controls;
using System.Windows.Data;
using LabelGou.App.Export;
using LabelGou.App.Services;
using Xunit;

namespace LabelGou.App.Tests;

/// <summary>
/// 第 85 棒②：① 步「表格显示区」里那一列<strong>看得见列名、看不见值</strong>。
/// <para>用户 2026-09-19 拿红箭头从 Excel 的 D 列（<c>张数/一开四</c>，六行有值）指到面板里那一列六格全空，
/// 问"导入表格后存在消失列可能？有时消失能正常读取打印？"。根因不在数据：<c>AutoGenerateColumns</c>
/// 把<strong>列名当绑定路径</strong>解析，而 <c>/</c> 在 WPF 的 PropertyPath 里是分隔符 —— 于是那一列取不到值，
/// 而 ②③④ 步按下标与整串比较取数照旧正常（所以他"打印还是对的"）。</para>
/// <para>下面第一条<strong>不测我们的代码</strong>，它钉的是平台事实：不修就真的是空。
/// 拿它当参照，第二条才证明"修的是真凶"而不是顺手把别的洞填上（§五-151 同族：判据不许自己夸自己）。</para>
/// </summary>
public class PreviewGridColumnBindingTests
{
    private static T OnSta<T>(Func<T> work)
        => StaWorker.RunAsync((_, _) => work(), null, CancellationToken.None).GetAwaiter().GetResult();

    /// <summary>一张三列的表：中间那列表头带斜杠（店里 9.21 肖有、谭聪 9.19、谢通程 9.18 三张真表都这么写）。</summary>
    private static DataRowView OneRow()
    {
        var table = new DataTable("Sheet1");
        table.Columns.Add("货号", typeof(string));
        table.Columns.Add("张数/一开四", typeof(string));
        table.Columns.Add("数量", typeof(string));
        table.Rows.Add("olu830-280", "4", "144");
        return (DataRowView)table.DefaultView[0];
    }

    /// <summary>
    /// 离线求一条绑定：<strong>先把 DataContext 摆好再挂绑定</strong>。
    /// 反过来（先 SetBinding 再赋 DataContext）在这条没有消息泵的路上不会回头重解析，取到的是空——
    /// 探针实测过，别把它当成"绑定失败"的证据（那是夹具在骗人，§五-151 同族）。
    /// </summary>
    private static string Show(DataRowView row, Binding binding)
    {
        var text = new TextBlock { DataContext = row };
        text.SetBinding(TextBlock.TextProperty, binding);
        return text.Text;
    }

    /// <summary>平台事实：列名当路径用，含斜杠的那一列取不到值——这就是"整列消失"的成因。</summary>
    [Fact]
    public void APlainPropertyPathCannotReadAColumnWhoseHeaderHasASlash() => OnSta(() =>
    {
        var row = OneRow();
        Assert.Equal("olu830-280", Show(row, new Binding("货号")));          // 正例：普通列名读得到
        Assert.Equal("4", Show(row, new Binding("[张数/一开四]")));           // 转义成索引读得到（证明值真在）
        var asPath = Show(row, new Binding("张数/一开四"));      // ← 自动生成列走的就是这一条
        Assert.True(asPath == "", $"斜杠那列这次取到值了（「{asPath}」）：平台陷阱变了形，修法要重看");
        return true;
    });

    /// <summary>修法：路径留空 + 按列名取格，斜杠与点都不再是分隔符。</summary>
    [Fact]
    public void TheRowCellConverterReadsThatSameColumn() => OnSta(() =>
    {
        var row = OneRow();
        var fixed0 = new Binding { Converter = new PreviewGridColumns.RowCell("张数/一开四") };
        Assert.Equal("4", Show(row, fixed0));
        return true;
    });

    /// <summary>什么字符都不怕：点、尾随空格、换行、右方括号、星号——这些都会要了 PropertyPath 的命。</summary>
    [Theory]
    [InlineData("张数/一开四")]
    [InlineData("尺寸.纸")]
    [InlineData("行号 ")]
    [InlineData("货号\nITEM NO:")]
    [InlineData("a]b")]
    [InlineData("1*2")]
    public void EveryOddHeaderStillResolvesToItsOwnValue(string header) => OnSta(() =>
    {
        var table = new DataTable();
        table.Columns.Add(header, typeof(string));
        table.Rows.Add("值在这");
        var row = (DataRowView)table.DefaultView[0];
        Assert.Equal("值在这", Show(row, new Binding { Converter = new PreviewGridColumns.RowCell(header) }));
        return true;
    });

    /// <summary>挂在自动生成事件上：那一列的绑定必须换成我们的转换器（路径不再拿列名去解析）。</summary>
    [Fact]
    public void TheAutoGeneratedColumnGetsTheConverterBinding() => OnSta(() =>
    {
        var column = new DataGridTextColumn();
        var args = new DataGridAutoGeneratingColumnEventArgs("张数/一开四", typeof(string), column);
        PreviewGridColumns.AutoGenerating(null, args);

        var binding = Assert.IsType<Binding>(column.Binding);
        var converter = Assert.IsType<PreviewGridColumns.RowCell>(binding.Converter);
        Assert.Equal("张数/一开四", converter.Header);
        Assert.True(string.IsNullOrEmpty(binding.Path?.Path),
            "还留着列名当路径 = 斜杠那列又会整列空掉");
        return true;
    });

    /// <summary>
    /// 取不到列就空着，<strong>不许猜到隔壁列去</strong>：① 步这张表是给人核对原表的，
    /// 把 B 列的值画到 C 列头上比空着更糟（那是"会印错且看不见"那一类）。
    /// </summary>
    [Fact]
    public void AMissingColumnReturnsEmptyInsteadOfSomebodyElsesValue() => OnSta(() =>
    {
        var row = OneRow();
        Assert.Equal("", Show(row, new Binding { Converter = new PreviewGridColumns.RowCell("没有这一列") }));
        return true;
    });
}
